import 'package:flutter/material.dart';

import '../../services/database_service.dart'; // استيراد الخدمة المحدثة
import '../../models/cart_model.dart';
import '../../widgets/web_footer.dart';
import '../../models/order_model.dart';
import '../../services/auth_service.dart';

class CheckoutScreen extends StatefulWidget {
  final double totalAmount;
  final List<CartItem> cartItems;

  const CheckoutScreen({
    super.key,
    required this.totalAmount,
    required this.cartItems,
  });

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  final _formKey = GlobalKey<FormState>();
  String _address = '';
  bool _isLoading = false;

  Future<void> _submitOrder() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();

    setState(() {
      _isLoading = true;
    });

    try {
      final user = AuthService().currentUser;
      if (user != null) {
        final order = OrderModel(
          id: '', // Generated by Firestore
          userId: user.id,
          userName: user.email ?? 'Unknown', // Ideally convert to user name
          items: widget.cartItems,
          totalAmount: widget.totalAmount,
          status: OrderStatus.pending,
          date: DateTime.now(),
          address: _address,
        );

        await DatabaseService().placeOrder(order);
        await DatabaseService().clearCart(user.id);

        if (!mounted) return;

        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (context) => AlertDialog(
            title: Text('تم الطلب بنجاح'),
            content: Text('شكراً لطلبك! سنتصل بك قريباً.'),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop(); // Close dialog
                  Navigator.of(context).pushNamedAndRemoveUntil(
                    '/',
                    (Route<dynamic> route) => false,
                  ); // Go Home
                },
                child: Text('حسناً'),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('حدث خطأ أثناء الطلب: $e')));
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('إتمام الشراء')),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  children: [
                    Text(
                      'إجمالي المبلغ: \$${widget.totalAmount.toStringAsFixed(2)}',
                      style: const TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      decoration: const InputDecoration(
                        labelText: 'عنوان التوصيل',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'يرجى إدخال العنوان';
                        }
                        return null;
                      },
                      onSaved: (value) {
                        _address = value ?? '';
                      },
                    ),
                    const SizedBox(height: 24),
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        onPressed: _submitOrder,
                        style: ElevatedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: 16),
                        ),
                        child: const Text(
                          'تأكيد الطلب',
                          style: TextStyle(fontSize: 18),
                        ),
                      ),
                    ),
                    if (MediaQuery.of(context).size.width > 800)
                      const WebFooter(),
                  ],
                ),
              ),
            ),
    );
  }
}
