import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart'; // ضروري لتحديد هوية المستخدم
import '../../services/database_service.dart'; // استيراد الخدمة المحدثة

<<<<<<< HEAD
class CheckoutScreen extends StatefulWidget {
  final double totalAmount;
  final List<CartItem> cartItems;

  const CheckoutScreen({
    super.key,
    required this.totalAmount,
    required this.cartItems,
  });

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  final _formKey = GlobalKey<FormState>();
  final String _address = '';
  bool _isLoading = false;

  Future<void> _submitOrder() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();

    setState(() {
      _isLoading = true;
    });

    try {
      final user = AuthService().currentUser;
      if (user != null) {
        final order = OrderModel(
          id: '', // Generated by Firestore
          userId: user.uid,
          userName: user.email ?? 'Unknown', // Ideally convert to user name
          items: widget.cartItems,
          totalAmount: widget.totalAmount,
          status: OrderStatus.pending,
          date: DateTime.now(),
          address: _address,
        );

        await DatabaseService().placeOrder(order);
        await DatabaseService().clearCart(user.uid);

        if (!mounted) return;

        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (context) => AlertDialog(
            title: Text('تم الطلب بنجاح'),
            content: Text('شكراً لطلبك! سنتصل بك قريباً.'),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop(); // Close dialog
                  Navigator.of(context).pushNamedAndRemoveUntil(
                    '/',
                    (Route<dynamic> route) => false,
                  ); // Go Home
                },
                child: Text('حسناً'),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('حدث خطأ أثناء الطلب: $e')));
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }
=======
class CheckoutScreen extends StatelessWidget {
  const CheckoutScreen({super.key});
>>>>>>> df094a09f831d15687de47dc41bd9a53678acd36

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser; // جلب المستخدم الحالي

    return Scaffold(
      appBar: AppBar(title: const Text('إتمام الشراء')),
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
            if (user != null) {
              try {
                // استدعاء الوظيفة التي قمنا بتعريفها في DatabaseService
                await DatabaseService().clearCart(user.uid);
                
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('تمت عملية الشراء بنجاح وتم مسح السلة')),
                );
                Navigator.popUntil(context, ModalRoute.withName('/'));
              } catch (e) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('حدث خطأ: $e')),
                );
              }
            }
          },
          child: const Text('تأكيد الطلب ومسح السلة'),
        ),
      ),
    );
  }
}
